#!/bin/bash
# Install Higgs Audio TTS V3 on this GPU node and register it with the cluster.
#
# Run once per GPU node. Re-running is safe (idempotent for venv + service setup).
# After running, add the node IP to litellm/.env on the Master VM and restart LiteLLM.
#
# Usage:
#   bash scripts/install_higgs_audio.sh [--gpu <id>] [--port <port>]
#
# Defaults:
#   GPU  = 0
#   PORT = 8881
#
# After install, point LiteLLM at this node:
#   On Master VM (10.2.35.10), edit litellm/.env:
#     HIGGS_AUDIO_HOST=http://<this-node-ip>:8881
#   Then: bash litellm/stop_proxy.sh && bash litellm/start_proxy.sh

set -e

# ── Configuration ─────────────────────────────────────────────────────────────
GPU_ID="${HIGGS_GPU:-0}"
PORT="${HIGGS_PORT:-8881}"
INSTALL_DIR="$HOME/higgs-audio"
VENV_DIR="$INSTALL_DIR/venv"
LOG_DIR="$HOME/logs"
LOG_FILE="$LOG_DIR/higgs-audio.log"
PID_FILE="$INSTALL_DIR/.higgs_pid"

# ── Higgs Audio source ────────────────────────────────────────────────────────
# Set HIGGS_AUDIO_REPO to override the default clone URL.
# Format: https://github.com/<owner>/<repo>.git
HIGGS_AUDIO_REPO="${HIGGS_AUDIO_REPO:-https://github.com/HiggsAudio/higgs-audio.git}"
HIGGS_AUDIO_BRANCH="${HIGGS_AUDIO_BRANCH:-main}"

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --gpu)   GPU_ID="$2";  shift 2 ;;
        --port)  PORT="$2";    shift 2 ;;
        --repo)  HIGGS_AUDIO_REPO="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── Prerequisites ─────────────────────────────────────────────────────────────
echo "=== Higgs Audio TTS V3 — Install Script ==="
echo "  GPU:   $GPU_ID"
echo "  Port:  $PORT"
echo "  Dir:   $INSTALL_DIR"
echo "  Repo:  $HIGGS_AUDIO_REPO"
echo ""

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found. Install Python 3.10+ first."
    exit 1
fi

if ! command -v git &>/dev/null; then
    echo "ERROR: git not found."
    exit 1
fi

if ! command -v nvidia-smi &>/dev/null; then
    echo "WARNING: nvidia-smi not found. Higgs Audio requires an NVIDIA GPU."
    echo "  Continuing anyway — set CUDA_VISIBLE_DEVICES=$GPU_ID manually if needed."
fi

# ── Clone / update repo ───────────────────────────────────────────────────────
mkdir -p "$LOG_DIR"

if [ -d "$INSTALL_DIR/.git" ]; then
    echo "→ Updating existing install at $INSTALL_DIR..."
    git -C "$INSTALL_DIR" pull origin "$HIGGS_AUDIO_BRANCH"
else
    echo "→ Cloning Higgs Audio into $INSTALL_DIR..."
    git clone --branch "$HIGGS_AUDIO_BRANCH" "$HIGGS_AUDIO_REPO" "$INSTALL_DIR"
fi

# ── Python venv + dependencies ────────────────────────────────────────────────
echo "→ Setting up Python venv at $VENV_DIR..."
python3 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"

echo "→ Installing Python dependencies..."
pip install --upgrade pip --quiet

# Install from requirements.txt if present; otherwise fall back to known deps.
if [ -f "$INSTALL_DIR/requirements.txt" ]; then
    pip install -r "$INSTALL_DIR/requirements.txt" --quiet
else
    echo "  (No requirements.txt found — installing baseline audio deps)"
    pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu124 --quiet
    pip install fastapi uvicorn pydantic --quiet
fi

deactivate
echo "  ✓ Dependencies installed"

# ── Create startup script ─────────────────────────────────────────────────────
# Adjust START_CMD below once the Higgs Audio V3 server entrypoint is confirmed.
# Common patterns:
#   python server.py --port $PORT
#   python -m higgs_audio.server --port $PORT
#   uvicorn higgs_audio.app:app --port $PORT
#
# After running the server, verify the API:
#   curl http://localhost:$PORT/v1/audio/speech \
#     -H "Content-Type: application/json" \
#     -d '{"model":"higgs-audio-tts","input":"Hello","voice":"<voice-id>"}' \
#     --output /tmp/test.mp3
#
# If the endpoint differs from /v1/audio/speech, update static_models.yaml
# and add a LiteLLM custom_provider or wrapper as needed.

START_SCRIPT="$INSTALL_DIR/start_server.sh"
cat > "$START_SCRIPT" <<STARTEOF
#!/bin/bash
# Auto-generated by install_higgs_audio.sh
# Edit START_CMD below if the Higgs Audio V3 entrypoint differs.

INSTALL_DIR="$INSTALL_DIR"
VENV_DIR="$VENV_DIR"
PORT="$PORT"
GPU_ID="$GPU_ID"
LOG_FILE="$LOG_FILE"
PID_FILE="$PID_FILE"

source "\$VENV_DIR/bin/activate"
export CUDA_VISIBLE_DEVICES="\$GPU_ID"

# ── START_CMD: update once server entrypoint is confirmed ──────────────────
# START_CMD="python \$INSTALL_DIR/server.py --port \$PORT --host 0.0.0.0"
# START_CMD="python -m higgs_audio.server --port \$PORT"
START_CMD="python \$INSTALL_DIR/server.py --port \$PORT --host 0.0.0.0"
# ──────────────────────────────────────────────────────────────────────────

mkdir -p "\$(dirname "\$LOG_FILE")"

if [ -f "\$PID_FILE" ]; then
    PID=\$(cat "\$PID_FILE")
    if kill -0 "\$PID" 2>/dev/null; then
        echo "Higgs Audio already running (PID \$PID)"
        exit 0
    fi
    rm -f "\$PID_FILE"
fi

echo "Starting Higgs Audio TTS V3 on GPU \$GPU_ID, port \$PORT..."
\$START_CMD >> "\$LOG_FILE" 2>&1 &
echo \$! > "\$PID_FILE"
echo "  PID: \$(cat \$PID_FILE)"
echo "  Log: \$LOG_FILE"

sleep 5
if kill -0 "\$(cat \$PID_FILE)" 2>/dev/null; then
    echo "Higgs Audio running — http://localhost:\$PORT"
    echo ""
    echo "  Verify: curl -s http://localhost:\$PORT/v1/audio/speech \\"
    echo "    -H 'Content-Type: application/json' \\"
    echo "    -d '{\"model\":\"higgs-audio-tts\",\"input\":\"Hello\",\"voice\":\"<id>\"}' \\"
    echo "    --output /tmp/higgs_test.mp3"
else
    echo "ERROR: Higgs Audio failed to start. Check \$LOG_FILE"
    rm -f "\$PID_FILE"
    exit 1
fi
STARTEOF
chmod +x "$START_SCRIPT"

STOP_SCRIPT="$INSTALL_DIR/stop_server.sh"
cat > "$STOP_SCRIPT" <<STOPEOF
#!/bin/bash
PID_FILE="$PID_FILE"
if [ -f "\$PID_FILE" ]; then
    PID=\$(cat "\$PID_FILE")
    if kill -0 "\$PID" 2>/dev/null; then
        echo "Stopping Higgs Audio (PID \$PID)..."
        kill "\$PID"
        rm -f "\$PID_FILE"
        echo "Stopped."
    else
        echo "Higgs Audio not running (stale PID file removed)"
        rm -f "\$PID_FILE"
    fi
else
    echo "Higgs Audio not running (no PID file)"
fi
STOPEOF
chmod +x "$STOP_SCRIPT"

# ── systemd service (optional) ────────────────────────────────────────────────
SERVICE_FILE="/etc/systemd/system/higgs-audio.service"
echo ""
echo "→ systemd service (optional, requires sudo)..."
if command -v systemctl &>/dev/null; then
    cat <<SERVICEEOF
  To install as a systemd service (auto-start on reboot), run:

  sudo tee $SERVICE_FILE > /dev/null <<'EOF'
[Unit]
Description=Higgs Audio TTS V3 Server
After=network.target

[Service]
Type=simple
User=$USER
ExecStart=$START_SCRIPT
Restart=on-failure
RestartSec=10
Environment=CUDA_VISIBLE_DEVICES=$GPU_ID

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable higgs-audio
  sudo systemctl start higgs-audio

SERVICEEOF
else
    echo "  (systemctl not found — skip systemd setup)"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
THIS_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
echo ""
echo "=== Install complete ==="
echo ""
echo "  Start:  bash $START_SCRIPT"
echo "  Stop:   bash $STOP_SCRIPT"
echo "  Logs:   $LOG_FILE"
echo ""
echo "  After starting, wire into the cluster proxy:"
echo "  On Master VM (10.2.35.10), add to litellm/.env:"
echo ""
echo "    HIGGS_AUDIO_HOST=http://${THIS_IP}:${PORT}"
echo ""
echo "  Then restart LiteLLM:"
echo "    bash litellm/stop_proxy.sh && bash litellm/start_proxy.sh"
echo ""
echo "  Next steps:"
echo "  1. Start the server:    bash $START_SCRIPT"
echo "  2. Verify the API:      curl http://localhost:$PORT/v1/audio/speech ..."
echo "  3. List available voices (check Higgs Audio docs/README for the endpoint)"
echo "  4. Fill in voice IDs in Foundation Coach:"
echo "     - frontend/lib/prospect.ts  (HIGGS_AUDIO_VOICES array)"
echo "     - backend/persona.py        (TTS_VOICES env var or VALID_VOICE_IDS)"
